# Generated by Django 3.2 on 2021-04-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
