# Generated by Django 3.2 on 2021-04-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_alter_survey_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
