# Generated by Django 3.2 on 2021-04-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0003_alter_useranswer_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'survey', 'question', 'answer_option')},
        ),
    ]
