# Generated by Django 3.2 on 2021-04-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0004_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
    ]
